import type { Metadata } from "next";
import { Monoton } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next";

import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";

const monoton = Monoton({
  subsets: ["latin"],
  weight: "400", // Monoton has only one weight
  variable: "--font-monoton",
  display: "swap",
});

export const metadata: Metadata = {
  title: "MEET.AI",
  description: "Generated by Aditya Raj",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <NuqsAdapter>
      <TRPCReactProvider>
        <html lang="en">
          <body className={`${monoton.className} antialiased`}>
            <Toaster />
            {children}
          </body>
        </html>
      </TRPCReactProvider>
    </NuqsAdapter>
  );
}